---
title: "Deskriptive Analyse"
output: html_document
---

## Employee Churn
# Prediction Martin

```{r}
library(readxl)
library(ggplot2)
library(tidyr)
library(stringr)
library(lubridate)
library(mltools)
library(data.table)
library(mlbench)
library(tidyverse)
library(magrittr)

#tree

library(caret)
library(caretEnsemble)
library(h2o)
h2o.init()

```


## Datenimport und -vorbereitung
```{r}
hot_df <- read_xlsx("20220110_dataPrepped_afterOneHot.xlsx")
hot_df <- subset(hot_df, 
                  select = -c(EmployeeChurned_1, `start_Cost center`,
                              `start_Calendar Year/Month`,
                              `LastActive_Calendar Year/Month`))


colnames(hot_df)[colnames(hot_df) == "EmployeeChurned_0"] <- "EmployeeChurned"
colnames(hot_df)[colnames(hot_df) == "Temporary_0"] <- "Temporary"

# Kategorische Variablen
factorCols <- c("Gender",
                "TemporaryPersonel",
                "Part Time Mark",
                "NonExempt",
                "start_NonExempt",
                "development to exempt",
                "Vertical_Horizontal_Developments_>= 3",
                "Vertical_Horizontal_Developments_0",
                "Vertical_Horizontal_Developments_1-2",
                "start_contract type_apprentice",
                "start_contract type_permanent staff",
                "start_contract type_temporary personnel",
                "start_Part time mark",
                "EmployeeChurned",
                "decrease_Category_Customer",
                "decrease_Category_GB Management",
                "decrease_Category_GBR/N",
                "decrease_Category_GTU GD",
                "decrease_Category_Human Resources GBS",
                "decrease_Category_Intellectual Property",
                "decrease_Category_IT Service CC",
                "decrease_Category_People",
                "decrease_Category_Planning & Development",
                "decrease_Category_Procurement Services - GP",
                "decrease_Category_RAA/A Competence",
                "decrease_Category_Safety",
                "decrease_Category_Supplier & Reporting",
                "Nationality_Classification_EU",
                "Nationality_Classification_German",
                "Nationality_Classification_Other",
                "Paybands_A",
                "Paybands_B",
                "Paybands_C",
                "Paybands_D",
                "Paybands_E",
                "Paybands_F",
                "Paybands_G",
                "Paybands_H")

# Umwandlung in kategorische Variablen
hot_df %<>% mutate_at(factorCols, factor)

#Indexspalte
#hot_df$index <- 1:nrow(hot_df)
str(hot_df)

```

## Train Test Split (Caret)
```{r}
head(hot_df)
#stratified random split (caret)
inTrain <- createDataPartition(y=hot_df$EmployeeChurned, p = .75, list=FALSE)

training <- hot_df[ inTrain,]
testing  <- hot_df[-inTrain,]

str(training)
str(testing)
```

## Train Test Split (sample)
```{r}
sortedDF <- sort(sample(nrow(hot_df), nrow(hot_df)*.7))
trainSample<-hot_df[sortedDF,]
testSample<-hot_df[-sortedDF,]
```

## Train Test Split (h2o)
```{r}
hot_dfH2O <- as.h2o(hot_df)
splits <- h2o.splitFrame(data =  hot_dfH2O, ratios = 0.75, seed = 1234)
trainH2O <- splits[[1]]
testH2O <- splits[[2]]
```

# Find Features
```{r}
#https://docs.h2o.ai/h2o/latest-stable/h2o-docs/data-science/model_selection.html

#automl
#https://docs.h2o.ai/h2o/latest-stable/h2o-docs/automl.html

#Grid Search
#Hyperparameter
```



# Einfacher Baum
```{r}
library(tree)

simpleTreeFit <- tree(trainSample$EmployeeChurned ~., data = trainSample)   #why?! Punkt funktioniert nicht... überall trainSample$... davor

plot(simpleTreeFit)
text(simpleTreeFit, pretty = 0)

```


#rpart initial
```{r}
library(rpart)
library(rpart.plot)

rpartInitial <- rpart(EmployeeChurned ~ Gender + 
                        `Month Of Service` +
                        `Months Since Last Development`,
                      data=trainSample,
                      control= rpart.control(cp=0.01))

rpartInitial <- rpart(EmployeeChurned ~. -index,
                      control= rpart.control(cp=0.01))

printcp(rpartInitial)
prp(rpartInitial)
```


#rpart specifications
```{r}
rpartFit <- rpart(EmployeeChurned ~ . -index, data = training, method = "class",control = rpart.control(maxdepth = 5, minsplit = 5))
rpart.plot(rpartFit)
#
```


#h2o Distributed Random Forest
```{r}
# Umwandlung in h2o-Dataframe
trainingH2O <- as.h2o(training)
testingH2O <- as.h2o(testing)

#predictors <- setdiff(colnames(titanic), colnames(titanic)[2:3])
predictors <- c("Gender", "Month Of Service" ,
                "Months Since Last Development",
                "Part Time Mark",
                "Paybands_A", "Paybands_B", "Paybands_C", "Paybands_D")
response <- "EmployeeChurned"


h2oFit <- h2o.randomForest(x = predictors,
                             y = response,
                             ntrees = 10,
                             max_depth = 5,
                             min_rows = 10,
                             min_split_improvement = 0.0001,
                             calibrate_model = FALSE,
                             binomial_double_trees = TRUE,
                             training_frame = trainingH2O,
                             nfolds = 6)


# Güte im Trainingsset
perf <- h2o.performance(h2oFit)
perf
h2o.confusionMatrix(h2oFit)

# Anwendung auf Testset
predict <- h2o.predict(h2oFit, newdata = testingH2O)
head(predict, 100)

# Güte anhand Testset
perfTest <- h2o.performance(h2oFit, testingH2O)
h2o.confusionMatrix(perfTest)

curve_data <- data.frame(perfTest@metrics$thresholds_and_metric_scores) %>% select(c(tpr,fpr))

ggplot(curve_data, aes(x = fpr, y = tpr)) +
    geom_point() +
    geom_line() +
    geom_segment(
        aes(x = 0, y = 0, xend = 1, yend = 1),
        linetype = "dotted",
        color = "grey50"
        ) +
    xlab("False Positive Rate") +
    ylab("True Positive Rate") +
    ggtitle("ROC Curve") +
    theme_bw()


#https://docs.h2o.ai/h2o/latest-stable/h2o-docs/performance-and-prediction.html?highlight=confusion%20matrix
```
#h2o XGBoost
```{r}
xgbFit <- h2o.xgboost(x = predictors,
                           y = response,
                           training_frame = trainingH2O,
                           booster = "dart",
                           normalize_type = "tree",
                           seed = 1234)
```


#caret train
```{r}
#test 
#hot_df$`Months Since Last Development`
treeFit <- train(EmployeeChurned ~ `Month Of Service`,
                     data = training,
                     method = "bstTree")
plot(treeFit)
text(treeFit, pretty =0)

#keine metrischen Werte
```
#caret predict
```{r}
treePredict <- predict(treeFit, newdata = testing)
#head(treePredict)
confusionMatrix(data = treePredict, testing$EmployeeChurned)
```


