---
title: "Prediction Regression"
output: html_document
---

## Employee Churn
# Prediction LogRegression
```{r}
library(readxl)
library(ggplot2)
library(tidyr)
library(stringr)
library(lubridate)
library(mltools)
library(data.table)
library(mlbench)
library(tidyverse)
library(magrittr)

library(rpart)
library(rpart.plot)
library(ROCR)
library(h2o)
h2o.init()

```

##Datenimport und Vorbereitung
```{r}
df <- read_xlsx("20220110_dataPrepped_beforeOneHot.xlsx")

# Kategorische Variablen umwandeln
factorCols <- c("EmployeeChurned",
                "decrease_Category",
                "Nationality_Classification",
                "Paybands")

df %<>% mutate_at(factorCols, factor)
# Auswählen der zu nutzenden Spalten auf Grund der ERgebnisse von Random Forrest
df <- subset(df, select = c(EmployeeChurned, decrease_Category, `Month Of Service`, `Months Since Last Development`, Age, Paybands, Nationality_Classification))

# Ansehen der Daten
plot(df, col=df$EmployeeChurned)
```

## Erstellen der Train und Test Datensets
```{r}
# n <- nrow(df)
# train_indices <- sample(1:n, round(2/3 * n))
# train <- df[train_indices,]
# test <- df[-train_indices,]
# 
# # erstmal 2 Features auswählen die die stärkste Abhängikeit nach den Trees haben
# features <- c("decrease_Category", "Month Of Service")
# cols <- c(features, "EmployeeChurned")

```

## H2O Vorbereitung und Umwandlung der Daten
```{r}
dfH2O <- as.h2o(df)

splits <- h2o.splitFrame(data =  dfH2O, ratios = 0.75, seed = 1234)
trainH2O <- splits[[1]]
testH2O <- splits[[2]]


#predictors <- c(factorCols, "Month Of Service", "Age", "Months Since Last Development")
# 6 Features auswählen die die stärkste Abhängikeit nach den Trees haben

predictors <- c("decrease_Category", 
                "Month Of Service",
                "Nationality_Classification",
                "Months Since Last Development",
                "Age",
                "Paybands",
                "Nationality_Classification")
response <- "EmployeeChurned"

```

```{r}
glm_model <- h2o.glm(family = "binomial",
                        x = predictors,
                        y = response,
                        training_frame = trainH2O,
                        lambda = 0,
                        compute_p_values = TRUE)
summary(glm_model)

h2o.std_coef_plot(glm_model)
best_glm <- h2o.getModel(glm_model@model_id)
best_glm
perf <- h2o.performance(best_glm, testH2O)
perf

```

## Auswahl Threshold
```{r}
# Anwendung auf Testset
pred <- h2o.predict(best_glm, newdata = testH2O)
Prediciton_df <- as.data.frame(pred)

asdf <- as.data.frame(testH2O)
asdf$prob <- Prediciton_df$p1

asdf$EmployeeChurned <- as.numeric(as.character(asdf$EmployeeChurned))

pred_rocr <- prediction(asdf$prob, asdf$EmployeeChurned)
perf_rocr <- performance(pred_rocr, "tpr", "fpr" )

performance(pred_rocr, "auc")@y.values
# Darstellung der ROC-Kurve
plot(perf_rocr, col="blue")
abline(0,1)

```













































## Datenimport und -vorbereitung
```{r}
# Datenset nach One-Hot-Encoding
hot_df <- read_xlsx("20220110_dataPrepped_afterOneHot.xlsx")
hot_df <- subset(hot_df, 
                  select = -c(EmployeeChurned_0, `start_Cost center`,
                              `start_Calendar Year/Month`,
                              `LastActive_Calendar Year/Month`))

colnames(hot_df)[colnames(hot_df) == "EmployeeChurned_1"] <- "EmployeeChurned"

# Kategorische Variablen
factorColsOneHot <- c("Gender",
                "TemporaryPersonel",
                "Part Time Mark",
                "NonExempt",
                "start_NonExempt",
                "development to exempt",
                "Vertical_Horizontal_Developments_>= 3",
                "Vertical_Horizontal_Developments_0",
                "Vertical_Horizontal_Developments_1-2",
                "start_contract type_apprentice",
                "start_contract type_permanent staff",
                "start_contract type_temporary personnel",
                "start_Part time mark",
                "EmployeeChurned",
                "decrease_Category_Customer",
                "decrease_Category_GB Management",
                "decrease_Category_GBR/N",
                "decrease_Category_GTU GD",
                "decrease_Category_Human Resources GBS",
                "decrease_Category_Intellectual Property",
                "decrease_Category_IT Service CC",
                "decrease_Category_People",
                "decrease_Category_Planning & Development",
                "decrease_Category_Procurement Services - GP",
                "decrease_Category_RAA/A Competence",
                "decrease_Category_Safety",
                "decrease_Category_Supplier & Reporting",
                "Nationality_Classification_EU",
                "Nationality_Classification_German",
                "Nationality_Classification_Other",
                "Paybands_A",
                "Paybands_B",
                "Paybands_C",
                "Paybands_D",
                "Paybands_E",
                "Paybands_F",
                "Paybands_G",
                "Paybands_H")

# Umwandlung in kategorische Variablen
hot_df %<>% mutate_at(factorColsOneHot, factor)

#Indexspalte
#hot_df$index <- 1:nrow(hot_df)



# Rohdatenset ohne One-Hot-Encoding
raw_df <- read_xlsx("20220110_dataPrepped_beforeOneHot.xlsx")

raw_df <- subset(raw_df, 
                  select = -c(`start_Cost center`,
                              `start_Calendar Year/Month`,
                              `LastActive_Calendar Year/Month`))

# Kategorische Variablen
factorCols <- c("Gender",
                "TemporaryPersonel",
                "Part Time Mark",
                "NonExempt",
                "start_NonExempt",
                "development to exempt",
                "Vertical_Horizontal_Developments",
                "start_contract type",
                "start_Part time mark",
                "EmployeeChurned",
                "decrease_Category",
                "Nationality_Classification",
                "Paybands")

raw_df %<>% mutate_at(factorCols, factor)
```

## Train Test Split (Caret)
```{r}
head(hot_df)
#stratified random split (caret)
inTrain <- createDataPartition(y=hot_df$EmployeeChurned, p = .75, list=FALSE)

training <- hot_df[ inTrain,]
testing  <- hot_df[-inTrain,]

str(training)
str(testing)
```

## Regression ohne h2o Beispiele (Block später löschen)
```{r}
glm1 <- glm(formula = training$EmployeeChurned ~ training$Age, family = binomial, data = training)
glm1

pre1 <- predict(glm1, type = 'response')

summary(glm1)
summary(pre1)

head(training)

plot(pre1)


training$predAge0.3 <- pre1
classify <- function(x, threshold){
  ifelse(x>threshold, 1, 0)
}

training$predAge0.3 <- classify(training$predAge0.3, 0.35)
c_matrix <- table(training$predAge0.5, training$EmployeeChurned)
c_matrix


```

```{r}
# # Umwandlung in h2o-Dataframe
# trainingH2O <- as.h2o(training)
# testingH2O <- as.h2o(testing)
# 
# predictors <- c(factorCols, "Month Of Service", "Age", "Months Since Last Development")
# response <- "EmployeeChurned"
# 
# h2oFit <- h2o.glm(x = predictors,
#                   y = response,
#                   training_frame = trainingH2O)
```

```{r}
df_test <- subset(hot_df, select = c("EmployeeChurned", "development to exempt", "Month Of Service"))
df <- data.frame(df_test)

LRModel <- glm()

```



